name: docker-spark-cluster
on:
  push:
    branches:
    - master
env:
  BASE_IMAGE: hub.docker.com/mvillarrealb
jobs:
  build-spark:
    runs-on: ubuntu-latest
    steps:
      - name: setup project
        id: checkout
        uses: actions/checkout@master
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build & publish image
        uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          push: true
          tags: ${{ env.BASE_IMAGE }}/apache-spark:${{ github.sha }}